### ISSUE TITLE
wrong effective field from biquad and 4spin in H%get_eff_field_single

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#112]
It seems there is a factor of 2 between the Beff fom H%get_eff_field_single and H%get_eff_field for the contributions of 4spin and biquad. The correct one should be the output of H%get_eff_field. This breaks minimize_infdamp.
commit #3223be9b0e46c97a83398d5a13a6fe6b1620cf4b

MWE
```
simulation minimize_infdamp 
convergence_criteria 1.0d-10


M_biq
1 1 1 2.96d-3 #between atoms 1 and 1, shell 1, amplitude in eV

M_4spin
1 2.14d-3 #atom type 1, amplitude in eV

atomtypes 2
Fe  3.0 0.0 0.0 F #mu_s in mu_B, z*, m, phonons T/F
Ir  0.0 0.0 0.0 F

atoms 2
Fe 0.0  0.0   0.0 #element, x y z in lattice vectors
Ir 0.5 0.5 -0.7

#writting deleting
gra_freq 2000
min_Efreq 1000

# parameters of the lattice
Periodic_log .T. .T. .F.
Nsize 50 50 1
alat 1.0 1.0 1.0
lattice
0.5 -0.86602540378 0.0
0.5 0.86602540378 0.0
0.0 0.0 1.0
```

**Comment by patrick432** [comment]
Hi Louise,

looking at that issue I have the strong suspicion, that the error occurs  in the get_eff_field_single routine in Hamiltonian_type/hamiltonian_collection.f90.

Compared to the energy single routine, an analog to the line
`if (this%NH_local.ne.0) tmp_E(:this%NH_local)=tmp_E(:this%NH_local)*real(this%H(:)%mult_M_single,8)` (348)
is not present in `get_eff_field_single`.

A bit of explanation:
The factor mult_M_single is set in the initialization of each energy, for example in the Heisenberg exchange (exchange_Heisenberg_J.f90).
 It is the last entry of the subroutine:
`Call Ham_tmp%init_connect(neigh%pairs(:,connect_bnd(1):connect_bnd(2)),val_tmp,ind_tmp,"MM",lat,2)`(113)
Hence, the single energy evaluation in case of the Heisenberg exchange is multiplied by 2.
This is necessary, as the easiest way to get the energy caused by one spin is to multipy the matrix to one side where the vector consists only of 0s on all site except for the entries of the considered spin. That way one gets the energy caused by the spin. However, since the energy matrix is considered as symmetric, half of the energy of the reverse interactions are missing. Hence, the factor 2 is necessary.

Similarly, this muliplicative factor is necessary when considering the 4spin-term. But now, there are 4 alternative interactions. Therefore the multiplicative factor mult_M_single is set as 4 as in the following call of 4spin.f90.
`Call Ham_tmp%init_mult_connect_2(connect,val_tmp,ind_tmp,"MM","MM",lat,4,dim_mode_in=dim_mode)`

When developing the get_eff_field_single I probably noticed for the rank2 magnetic interactions that the multiplication with 2 is not necessary. Most probably as one only mutiplied the matrix to one side so that there is no double counting. There was a discussion about this mainly with Bertrand, but I think you where also there.

It makes sense that the mutiple counting is relevant though for 4-spin interactions. 
Since you saw that it is a simple multiplicative factor of 2, one could suspect that one simply would have to add something like:
`if (this%NH_local.ne.0) B(:this%NH_local)=B(:this%NH_local)*real(this%H(:)%mult_M_single,8)*0.5_8`

However, one should probably think it through if in general it is always that easily related to the single term necessary to for the single_energy rescaling. Naively, I would not have been surprised if it would have been a factor 3 or something more complicated depending of the structure of the interactions. Actually, without thinking more about it I am rather surpised that it is also a factor 2 for the biquadratic terms...
So Bertrand should probably try to figure out if there is a general way to solve that.

**Comment by bertdupe** [comment]
Hello both,

for the 4spin it should be a factor of 4 and for the big as well.
However, if I look into the routine, it is a factor of 2
                    Call Ham_tmp%init_mult_connect_2(neigh%pairs(:,connect_bnd(1):connect_bnd(2)),val_tmp,ind_tmp,"MM","MM",lat,2,[9*Nmag,9*Nmag])

unless, of course, when you do the left and right operation before the, you put a factor of 2. In the code there is a factor one there
Call mode_set_rankN_sparse(Ham%mode_l,"MM",lat,mat,1).

when I compare with the 4-spin, the line
Ham_tmp%init_mult_connect_2(neigh%pairs(:,connect_bnd(1):connect_bnd(2)),val_tmp,ind_tmp,"MM","MM",lat,2,[9*Nmag,9*Nmag])

should be changed to
Ham_tmp%init_mult_connect_2(neigh%pairs(:,connect_bnd(1):connect_bnd(2)),val_tmp,ind_tmp,"MM","MM",lat,4,[9*Nmag,9*Nmag])

Would that be a solution?

**Comment by patrick432** [comment]
Hi Bertrand,

I am really not sure if the biquadratic term should have the factor 4 as well, since one acts on the same spin twice.
So far I would understand the scaling factor as only scaling the energy to correctly get the single energy.
This can be tested compared to the overall energy routine and should be correct. 
Thus, I think if you change the biquadratic factor in `init_mult_connect_2` to 4, the single energies would no longer be correct. 

Also, I am not sure if you or I misunderstood the problem, but I think the energies are actually correct and only the "single" effective field should also be doubled in some cases. 
So far, the single effective fields are not influenced by the factors in the `init_mult_connect_2` anyways, so that a scaling there would also be necessary.

However, since you stated correctly that the biquadratic term has a factor 2 instead of 4, but also needs to be doubled as found out by Louise, something more drastic has to be done anyways. 
The solution I suggested above will not work due to the differing scaling factors for the energy terms.

What the factor argument of `mode_set_rankN_sparse`  does is that it sets the element `%mult_M_single`, which was done rather hastily to get the montecarlo running correctly. The `1` in `mode_set_rankN_sparse` has nothing to do with that but is an argument to switch between different implementations of how the describe the more complicated left/right basis of the Hamiltonian. 

I think there are 2 ways to solve this issue.
Either one has to think in more detail about what is the correct scaling of the effective fields is and how one can deduce that from the implemented quantities.
Alternatively, one can implement an analogous scaling factor for the single effective magnetic field and add this analogous to whereever the `%mult_M_single` term appears.

**Comment by bertdupe** [comment]
yo,
ok it does not but it does a bit since the derivative is based on the Hamiltonian form... And yet, if I change this factor, I will indeed destroy ht single energy term in the MC...
It is try that the energy should be multiplied by 2 for the biq in the MC and by 4 in the 4-spin.
But then the question is how did you do for the anisotropy?  Because indeed, it is an onsite term but you have a 2 in the derivative. As far as I understood, you are saved thanks to the left and right multiplication no ?

**Comment by bertdupe** [comment]
the problem is that I find the code logical that way.
if we change the routine, I am afraid that the Torques will be wrong... There are 2 different things:
- the _single stuff which is the routine that gets the torques at each site,
- the derivation of the Hamiltonian with respect to M
the difference between the two is a factor of 2 actually. I still did not look in the anisotropy though because the same factor of 2 should appear there actually

**Comment by bertdupe** [comment]
this has been corrected actually.
