### ISSUE TITLE
wrong 4spin energy for 2at/uc

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#127]
For a 2Q state, 4spin energy potentially twice too large?

MWE:
init.config:
```
configuration_magnetic 2Q
Q1_magnetic  0.707106781186548   0.707106781186547                   0
Q2_magnetic      -0.707106781186547   0.707106781186548                   0
Qnorm_magnetic         0.707106781186547

```
input:
```
simulation magnet-dynamics 

M_4spin
1 -1.05d-3 #atom type 1, amplitude in eV

magnetic_J
1 1 1 5.7d-3     #between atoms 1 and 1, shell 1, amplitude in eV


atomtypes 2
Fe  2.7 0.0 0.0 F #mu_s in mu_B, z*, m, phonons T/F
Ir  0.0 0.0 0.0 F
atoms 3
Fe 0.0  0.0   0.0 #element, x y z in lattice vectors
Fe 0.5 0.5 0.0
Ir 0.5 0.5 -0.7


#writting deleting
Energy_Distrib .F.
gra_fft .F.
gra_log .T.
gra_Beff .F.
gra_freq 1
min_Efreq 1
gra_topo .F.
calc_topo F
print_Econt T
energy_detail T

# parameters of the lattice
Periodic_log .T. .T. .F.
Nsize 2 2 1 
alat 1.0 1.0 1.0
lattice
1.0 0.0 0.0
0.0 1.732050807568877 0.0
0.0 0.0 1.0



#input for the dynamic
integration 2  (1: simple integration 2:Heun  3: SIB ) 
timestep 0.0000001 (fs)
duration 1 (in units of dt)
damping 0.1

```

**Comment by bertdupe** [comment]
the 4-spin was checked. It will be in the test of the code because it is really really really really really annoying.
3 calculations:
- 1at/cl and a 2x2 with open boundary conditions - 4 magnetic moment rotated slowly from theta=0 to 90. At the end, they should all point toward a point which is in the middle of the diamond. The results is then analytical and falls on the point
- 2 at/cl with with 2x1 supercell in closed boundary conditions should give the same with a 4x4 with 1 at/cl with the exact same magnetic configuration as the previous one. The energy of the 2 at/cl should be exactly twice as the 1at/cl.

the 4 spin does not work with 2at/cl and open boundary conditions - and I do not care.
