### ISSUE TITLE
edit: fft for electric dipole not working

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#133]
Currently having 3 main issues with electric dipole hamiltonian:

1) It seems only the real space dipole hamiltonian can be set in the current version. I tried to add the ftt equilivalent (commit #02d4f35bc06384828d0ec474af428dada4f93e18 on my branch), it compiles but segfaults on execution. Did not attempt debugging. yet. keyword is `ph_dip_fft T`

2) When testing the ddi energy from 2 sites with open boundary conditions, it seems the equilibrium position of the atoms is used to compute the dipole matrix and thus energy, but the atomic displacements are not taken into account? From my understanding of how matjes is coded, the purpose of the `dipolar_phonon `module is to evaluate the matrix A such that Edip=u'Au. My issue here is that while in magnetism, A does not depend on m, when considering atomic displacements it should depend on R0+u and therefore on u, where R0 are the equilibrium positions? currently this is not the case. when adding u in the diff vector calculation, I guess the initial value of Edip is correct but then it is never updated.

3) lastly, if one ignores issue 2), I still have a factor of 2 when comparing outputed value to what im expecting for the input below for the dipolar energy (expecting 0.61 meV total, getting 0.3059 meV total). maybe i am just confused.  

NB I have changed the ph dipole prefactor so that the born effective charge is in units of electron charge in input. This is only on my branch so far. Otherwise one needs to set values like 1e-19 in the input.

input: 
```
simulation molecular_dynamics
H_ext 0.0 0.0 0.0 # T

#force_tensor
#1 1 1 10.0d-5 0.0d0 0.0d0 0.0d0 10.0d-5 0.0d0 0.0d0 0.0d0 10.0d-5 1.0 0.0 0.0 #1 1 1 Fxx Fxy Fxz Fyx Fyy Fyz Fzx Fzy Fzz Rx Ry Rz

phonon_harmonic
1 1 1 1.0d-3 #eV/nm2
set_ASR T

DDI
ph_dip_use T
ph_dip_fft F
ph_dip_period_cut 5 5  1

atomtypes  1
Na  0.0 1.0 47.0 T 0

atoms 1
Na   0.0  0.0   0.0

# parameters of the lattice
Periodic_log .F. .F. .F.
Nsize 2 1 1
alat 1.0 1.0 1.0
lattice
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0


#input for the dynamic
integration 2  (1: simple integration 2:Heun  3: SIB ) 
timestep 10 (fs)
duration 1 (in units of dt)
damping 0.0


#output
gra_topo .F.
gra_fft .F.
gra_log .T.
gra_Beff .F.
gra_freq 1
Efreq 1
CalTheta .F.
Energy_Distrib .F.
energy_detail .T. 
print_Econt .T.
```

init.config:
```
configuration_phonon spiral
# vector of the SS and 2 vectors for the polarization
qvec_phonon 0.0 0.0 0.0
Rq_phonon 1.0 0.0 0.0
Iq_phonon 0.0 1.0 0.0
norm_phonon 0.01
q_norm_phonon 0.5 0.0 0.0

```

**Comment by loudesplat** [comment]
Update:
2. solved by considering Rij as the equilibrium atom positions as in [Zhong and Vanderbilt, PRB 52, 1995]
3. 0.28meV for dipole is indeed correct, no factor of 2

so only 1. remains as issue.

**Comment by patrick432** [comment]
Hi Louise,
I looked into that, and it seems that the FFT-implementation always assumed, that the operations are done on the magnetic order-parameter. 
I have tried to extend the functionality, so that it could also work with other order parameters. The results of that are pushed in the branch [FFT_dipolar_no_crash](https://github.com/bertdupe/Matjes/tree/FFT_dipolar_no_crash). 
Now, one needs to supply the order-parameter in the form of a character(1) as an additional parameter to the H_fft%init_shape subroutine.

I have implemented this to the point, that your input with ph_dip_fft does not crash, however the results differ.
Since I did not implement the dipolar_phonon.f90, I am not sure about if the error is in there or in the deeper fft-routines. 
Also, if you continue with this changes, you might want to check if the magnetic fft is still the same as the non-fft version, it is possible that I have introduced an error.
I don't really have the knowledge or time to test this thoroughly, but I hope this helps you moving forward.

Best wishes,
Patrick

**Comment by loudesplat** [comment]
closing issue #138 but energy distrib may need to be implemented for fft hamil for phonon

**Comment by loudesplat** [comment]
needs to be finished

**Comment by bertdupe** [comment]
repaired. Did not check for specific numbers

**Comment by loudesplat** [comment]
quick check seems fine, fft dipole  gives same result as real space dipole.
N=2 with open BC and kx=0.5, us=0.01 gives me 0.28 meV total in both cases like in my previous message.
[commit #e068ad9ec4dc08d3aef6f57eda6e7a3c4dc3cd8f]
![Eph_vs_us_xchain_Edip_fft_vs_nofft](https://github.com/bertdupe/Matjes/assets/37928020/e0a6a49a-328f-42aa-a6f6-78c4ba448cf7)
