### ISSUE TITLE
problem anisotropy

### ISSUE THREAD

**Issue by loudesplat** [bertdupe/Matjes#61]
I think the anistropy does not work properly in the latest versions (energy always >0?). anisotropy_lat seems to work but may have an accuracy issue with a nontrivial lattice and more than one easy axis.

**Comment by patrick432** [comment]
Changed the input so that the sign of the first non-zero entry is used for the normal anisotropy. 
Alternatively, the magnitude can be given as a 4th entry.

The anisotropy_lat error description is too vague for me to understand.
Is it the expected accuracy error stemming from the rotation due to the representation of real values (~16 orders of magnitude smaller?)
